using System;
using System.ComponentModel;
using System.Globalization;
using BH.oM.Base;
using Newtonsoft.Json;

namespace BH.oM.Adapters.EnergyPlus.ElectricLoadCenterGeneratorSpecifications
{
    [Description(@"This generator model is the empirical model from the Building Loads and System Thermodynamics (BLAST) program. Generator performance curves are generated by fitting catalog data to second order polynomial equations. Three sets of coefficients are required.")]
    public class Generator_CombustionTurbine : BHoMObject, IEnergyPlusClass
    {
        

        [JsonProperty("rated_power_output")]
        public System.Nullable<float> RatedPowerOutput { get; set; } = null;
        

        [JsonProperty("electric_circuit_node_name")]
        public string ElectricCircuitNodeName { get; set; } = "";
        

        [JsonProperty("minimum_part_load_ratio")]
        public System.Nullable<float> MinimumPartLoadRatio { get; set; } = null;
        

        [JsonProperty("maximum_part_load_ratio")]
        public System.Nullable<float> MaximumPartLoadRatio { get; set; } = null;
        

        [JsonProperty("optimum_part_load_ratio")]
        public System.Nullable<float> OptimumPartLoadRatio { get; set; } = null;
        

        [Description("curve = a + b*PLR + c*PLR**2 PLR = Ratio of Generator Load to Rated Power Output " +
                     "this curve is multiplied to the Temperature Based Fuel Input Curve to determine " +
                     "Fuel Energy In")]
        [JsonProperty("part_load_based_fuel_input_curve_name")]
        public string PartLoadBasedFuelInputCurveName { get; set; } = "";
        

        [Description("curve = a + b*AT + c*AT**2 AT = Ambient Delta T this curve is multiplied to the P" +
                     "art Load Based Fuel Input Curve to determine Fuel Energy In")]
        [JsonProperty("temperature_based_fuel_input_curve_name")]
        public string TemperatureBasedFuelInputCurveName { get; set; } = "";
        

        [Description("curve = a + b*AT + c*AT**2 AT = Ambient Delta T")]
        [JsonProperty("exhaust_flow_curve_name")]
        public string ExhaustFlowCurveName { get; set; } = "";
        

        [Description("curve = a + b*PLR + c*PLR**2 PLR = Ratio of Generator Load to Rated Power Output " +
                     "this curve is multiplied to the Temperature Based Exhaust Temperature Curve to d" +
                     "etermine Exhaust Temperature")]
        [JsonProperty("part_load_based_exhaust_temperature_curve_name")]
        public string PartLoadBasedExhaustTemperatureCurveName { get; set; } = "";
        

        [Description("curve = a + b*AT + c*AT**2 AT = Ambient Delta T this curve is multiplied to the P" +
                     "art Load Based Exhaust Temperature Curve to determine Exhaust Temperature")]
        [JsonProperty("temperature_based_exhaust_temperature_curve_name")]
        public string TemperatureBasedExhaustTemperatureCurveName { get; set; } = "";
        

        [Description("curve = a + b*PLR + c*PLR**2 PLR = Ratio of Generator Load to Rated Power Output")]
        [JsonProperty("heat_recovery_lube_energy_curve_name")]
        public string HeatRecoveryLubeEnergyCurveName { get; set; } = "";
        

        [Description("curve = C1 * Rated Power Output**C2")]
        [JsonProperty("coefficient_1_of_u_factor_times_area_curve")]
        public System.Nullable<float> Coefficient1OfUFactorTimesAreaCurve { get; set; } = null;
        

        [Description("curve = C1 * Rated Power Output**C2 typical value .9")]
        [JsonProperty("coefficient_2_of_u_factor_times_area_curve")]
        public System.Nullable<float> Coefficient2OfUFactorTimesAreaCurve { get; set; } = null;
        

        [JsonProperty("maximum_exhaust_flow_per_unit_of_power_output")]
        public System.Nullable<float> MaximumExhaustFlowPerUnitOfPowerOutput { get; set; } = null;
        

        [JsonProperty("design_minimum_exhaust_temperature")]
        public System.Nullable<float> DesignMinimumExhaustTemperature { get; set; } = null;
        

        [JsonProperty("design_air_inlet_temperature")]
        public System.Nullable<float> DesignAirInletTemperature { get; set; } = null;
        

        [JsonProperty("fuel_higher_heating_value")]
        public System.Nullable<float> FuelHigherHeatingValue { get; set; } = null;
        

        [Description("if non-zero, then inlet, outlet nodes must be entered.")]
        [JsonProperty("design_heat_recovery_water_flow_rate")]
        public System.Nullable<float> DesignHeatRecoveryWaterFlowRate { get; set; } = (System.Nullable<float>)Single.Parse("0", CultureInfo.InvariantCulture);
        

        [JsonProperty("heat_recovery_inlet_node_name")]
        public string HeatRecoveryInletNodeName { get; set; } = "";
        

        [JsonProperty("heat_recovery_outlet_node_name")]
        public string HeatRecoveryOutletNodeName { get; set; } = "";
        

        [JsonProperty("fuel_type")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Generator_CombustionTurbine_FuelType FuelType { get; set; } = (Generator_CombustionTurbine_FuelType)Enum.Parse(typeof(Generator_CombustionTurbine_FuelType), "NaturalGas");
        

        [JsonProperty("heat_recovery_maximum_temperature")]
        public System.Nullable<float> HeatRecoveryMaximumTemperature { get; set; } = (System.Nullable<float>)Single.Parse("80", CultureInfo.InvariantCulture);
        

        [Description("Enter the name of an outdoor air node")]
        [JsonProperty("outdoor_air_inlet_node_name")]
        public string OutdoorAirInletNodeName { get; set; } = "";
    }
}