using System;
using System.ComponentModel;
using BH.oM.Base;
using Newtonsoft.Json;

namespace BH.oM.Adapters.EnergyPlus.OutputReporting
{
    [Description("This object does not come from a user input. This is generated by a pre-processor" +
                 " so that various conditions can be gracefully passed on by the InputProcessor.")]
    [JsonObject("Output:PreprocessorMessage")]
    public class Output_PreprocessorMessage : BHoMObject
    {
        

        [JsonProperty("preprocessor_name")]
        public string PreprocessorName { get; set; } = "";
        

        [Description("Depending on type, InputProcessor may terminate the program.")]
        [JsonProperty("error_severity")]
        public EmptyNoYes ErrorSeverity { get; set; } = (EmptyNoYes)Enum.Parse(typeof(EmptyNoYes), "Empty");
        

        [JsonProperty("message_line_1")]
        public string MessageLine1 { get; set; } = "";
        

        [JsonProperty("message_line_2")]
        public string MessageLine2 { get; set; } = "";
        

        [JsonProperty("message_line_3")]
        public string MessageLine3 { get; set; } = "";
        

        [JsonProperty("message_line_4")]
        public string MessageLine4 { get; set; } = "";
        

        [JsonProperty("message_line_5")]
        public string MessageLine5 { get; set; } = "";
        

        [JsonProperty("message_line_6")]
        public string MessageLine6 { get; set; } = "";
        

        [JsonProperty("message_line_7")]
        public string MessageLine7 { get; set; } = "";
        

        [JsonProperty("message_line_8")]
        public string MessageLine8 { get; set; } = "";
        

        [JsonProperty("message_line_9")]
        public string MessageLine9 { get; set; } = "";
        

        [JsonProperty("message_line_10")]
        public string MessageLine10 { get; set; } = "";
    }
}