using System;
using System.ComponentModel;
using System.Globalization;
using BH.oM.Base;
using Newtonsoft.Json;

namespace BH.oM.Adapters.EnergyPlus.PlantHeatingandCoolingEquipment
{
    [Description("This chiller model is the empirical model from the Building Loads and System Ther" +
                 "modynamics (BLAST) program. Chiller performance curves are generated by fitting " +
                 "catalog data to third order polynomial equations. Three sets of coefficients are" +
                 " required.")]
    public class Chiller_EngineDriven : BHoMObject, IEnergyPlusClass
    {
        

        [JsonProperty("condenser_type")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Chiller_EngineDriven_CondenserType CondenserType { get; set; } = (Chiller_EngineDriven_CondenserType)Enum.Parse(typeof(Chiller_EngineDriven_CondenserType), "AirCooled");
        

        [JsonProperty("nominal_capacity")]
        public string NominalCapacity { get; set; } = "";
        

        [Description("Nominal Refrigeration Cycle COP")]
        [JsonProperty("nominal_cop")]
        public System.Nullable<float> NominalCop { get; set; } = null;
        

        [JsonProperty("chilled_water_inlet_node_name")]
        public string ChilledWaterInletNodeName { get; set; } = "";
        

        [JsonProperty("chilled_water_outlet_node_name")]
        public string ChilledWaterOutletNodeName { get; set; } = "";
        

        [JsonProperty("condenser_inlet_node_name")]
        public string CondenserInletNodeName { get; set; } = "";
        

        [JsonProperty("condenser_outlet_node_name")]
        public string CondenserOutletNodeName { get; set; } = "";
        

        [JsonProperty("minimum_part_load_ratio")]
        public System.Nullable<float> MinimumPartLoadRatio { get; set; } = null;
        

        [JsonProperty("maximum_part_load_ratio")]
        public System.Nullable<float> MaximumPartLoadRatio { get; set; } = null;
        

        [JsonProperty("optimum_part_load_ratio")]
        public System.Nullable<float> OptimumPartLoadRatio { get; set; } = null;
        

        [JsonProperty("design_condenser_inlet_temperature")]
        public System.Nullable<float> DesignCondenserInletTemperature { get; set; } = null;
        

        [JsonProperty("temperature_rise_coefficient")]
        public System.Nullable<float> TemperatureRiseCoefficient { get; set; } = null;
        

        [JsonProperty("design_chilled_water_outlet_temperature")]
        public System.Nullable<float> DesignChilledWaterOutletTemperature { get; set; } = null;
        

        [Description("For variable volume this is the maximum flow and for constant flow this is the fl" +
                     "ow.")]
        [JsonProperty("design_chilled_water_flow_rate")]
        public string DesignChilledWaterFlowRate { get; set; } = "";
        

        [Description("This field is not used for Condenser Type = AirCooled or EvaporativelyCooled")]
        [JsonProperty("design_condenser_water_flow_rate")]
        public string DesignCondenserWaterFlowRate { get; set; } = "";
        

        [JsonProperty("coefficient_1_of_capacity_ratio_curve")]
        public System.Nullable<float> Coefficient1OfCapacityRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_2_of_capacity_ratio_curve")]
        public System.Nullable<float> Coefficient2OfCapacityRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_3_of_capacity_ratio_curve")]
        public System.Nullable<float> Coefficient3OfCapacityRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_1_of_power_ratio_curve")]
        public System.Nullable<float> Coefficient1OfPowerRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_2_of_power_ratio_curve")]
        public System.Nullable<float> Coefficient2OfPowerRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_3_of_power_ratio_curve")]
        public System.Nullable<float> Coefficient3OfPowerRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_1_of_full_load_ratio_curve")]
        public System.Nullable<float> Coefficient1OfFullLoadRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_2_of_full_load_ratio_curve")]
        public System.Nullable<float> Coefficient2OfFullLoadRatioCurve { get; set; } = null;
        

        [JsonProperty("coefficient_3_of_full_load_ratio_curve")]
        public System.Nullable<float> Coefficient3OfFullLoadRatioCurve { get; set; } = null;
        

        [Description("Special EngineDriven Chiller Parameters Below")]
        [JsonProperty("chilled_water_outlet_temperature_lower_limit")]
        public System.Nullable<float> ChilledWaterOutletTemperatureLowerLimit { get; set; } = null;
        

        [Description("Curve is a function of Part Load Ratio (PLR) curve = a + b*PLR + c*PLR**2 PLR = R" +
                     "atio of evaporator heat transfer rate to nominal capacity")]
        [JsonProperty("fuel_use_curve_name")]
        public string FuelUseCurveName { get; set; } = "";
        

        [Description("Curve is a function of Part Load Ratio (PLR) curve = a + b*PLR + c*PLR**2 PLR = R" +
                     "atio of evaporator heat transfer rate to nominal capacity")]
        [JsonProperty("jacket_heat_recovery_curve_name")]
        public string JacketHeatRecoveryCurveName { get; set; } = "";
        

        [Description("Curve is a function of Part Load Ratio (PLR) curve = a + b*PLR + c*PLR**2 PLR = R" +
                     "atio of evaporator heat transfer rate to nominal capacity")]
        [JsonProperty("lube_heat_recovery_curve_name")]
        public string LubeHeatRecoveryCurveName { get; set; } = "";
        

        [Description("Curve is a function of Part Load Ratio (PLR) curve = a + b*PLR + c*PLR**2 PLR = R" +
                     "atio of evaporator heat transfer rate to nominal capacity")]
        [JsonProperty("total_exhaust_energy_curve_name")]
        public string TotalExhaustEnergyCurveName { get; set; } = "";
        

        [Description("Curve is a function of Part Load Ratio (PLR) curve = a + b*PLR + c*PLR**2 PLR = R" +
                     "atio of evaporator heat transfer rate to nominal capacity")]
        [JsonProperty("exhaust_temperature_curve_name")]
        public string ExhaustTemperatureCurveName { get; set; } = "";
        

        [Description("curve = C1 * (nominal capacity)**C2")]
        [JsonProperty("coefficient_1_of_u_factor_times_area_curve")]
        public System.Nullable<float> Coefficient1OfUFactorTimesAreaCurve { get; set; } = null;
        

        [Description("curve = C1 * (nominal capacity)**C2 typical value .9")]
        [JsonProperty("coefficient_2_of_u_factor_times_area_curve")]
        public System.Nullable<float> Coefficient2OfUFactorTimesAreaCurve { get; set; } = null;
        

        [JsonProperty("maximum_exhaust_flow_per_unit_of_power_output")]
        public System.Nullable<float> MaximumExhaustFlowPerUnitOfPowerOutput { get; set; } = null;
        

        [JsonProperty("design_minimum_exhaust_temperature")]
        public System.Nullable<float> DesignMinimumExhaustTemperature { get; set; } = null;
        

        [JsonProperty("fuel_type")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Chiller_EngineDriven_FuelType FuelType { get; set; } = (Chiller_EngineDriven_FuelType)Enum.Parse(typeof(Chiller_EngineDriven_FuelType), "Diesel");
        

        [JsonProperty("fuel_higher_heating_value")]
        public System.Nullable<float> FuelHigherHeatingValue { get; set; } = null;
        

        [Description("If non-zero, then the heat recovery inlet and outlet node names must be entered.")]
        [JsonProperty("design_heat_recovery_water_flow_rate")]
        public string DesignHeatRecoveryWaterFlowRate { get; set; } = (System.String)"0";
        

        [JsonProperty("heat_recovery_inlet_node_name")]
        public string HeatRecoveryInletNodeName { get; set; } = "";
        

        [JsonProperty("heat_recovery_outlet_node_name")]
        public string HeatRecoveryOutletNodeName { get; set; } = "";
        

        [Description(@"Select operating mode for fluid flow through the chiller. ""NotModulated"" is for either variable or constant pumping with flow controlled by the external plant system. ""ConstantFlow"" is for constant pumping with flow controlled by chiller to operate at full design flow rate. ""LeavingSetpointModulated"" is for variable pumping with flow controlled by chiller to vary flow to target a leaving temperature setpoint.")]
        [JsonProperty("chiller_flow_mode")]
        [Newtonsoft.Json.JsonConverter(typeof(Newtonsoft.Json.Converters.StringEnumConverter))]
        public Chiller_EngineDriven_ChillerFlowMode ChillerFlowMode { get; set; } = (Chiller_EngineDriven_ChillerFlowMode)Enum.Parse(typeof(Chiller_EngineDriven_ChillerFlowMode), "NotModulated");
        

        [JsonProperty("maximum_temperature_for_heat_recovery_at_heat_recovery_outlet_node")]
        public System.Nullable<float> MaximumTemperatureForHeatRecoveryAtHeatRecoveryOutletNode { get; set; } = (System.Nullable<float>)Single.Parse("60", CultureInfo.InvariantCulture);
        

        [Description("Multiplies the autosized capacity and flow rates")]
        [JsonProperty("sizing_factor")]
        public System.Nullable<float> SizingFactor { get; set; } = (System.Nullable<float>)Single.Parse("1", CultureInfo.InvariantCulture);
        

        [Description(@"This field is only used for Condenser Type = EvaporativelyCooled and for periods when the basin heater is available (field Basin Heater Operating Schedule Name). For this situation, the heater maintains the basin water temperature at the basin heater setpoint temperature when the outdoor air temperature falls below the setpoint temperature. The basin heater only operates when the chiller is not operating.")]
        [JsonProperty("basin_heater_capacity")]
        public System.Nullable<float> BasinHeaterCapacity { get; set; } = (System.Nullable<float>)Single.Parse("0", CultureInfo.InvariantCulture);
        

        [Description("This field is only used for Condenser Type = EvaporativelyCooled. Enter the outdo" +
                     "or dry-bulb temperature when the basin heater turns on.")]
        [JsonProperty("basin_heater_setpoint_temperature")]
        public System.Nullable<float> BasinHeaterSetpointTemperature { get; set; } = (System.Nullable<float>)Single.Parse("2", CultureInfo.InvariantCulture);
        

        [Description(@"This field is only used for Condenser Type = EvaporativelyCooled. Schedule values greater than 0 allow the basin heater to operate whenever the outdoor air dry-bulb temperature is below the basin heater setpoint temperature. If a schedule name is not entered, the basin heater is allowed to operate throughout the entire simulation.")]
        [JsonProperty("basin_heater_operating_schedule_name")]
        public string BasinHeaterOperatingScheduleName { get; set; } = "";
        

        [Description("This optional field is the fraction of total rejected heat that can be recovered " +
                     "at full load. Also used to autosize Design Heat Recovery Water Flow Rate as a fr" +
                     "action of Design Condenser Water Flow Rate.")]
        [JsonProperty("condenser_heat_recovery_relative_capacity_fraction")]
        public System.Nullable<float> CondenserHeatRecoveryRelativeCapacityFraction { get; set; } = null;
    }
}